#!/bin/sh
#
# A hook script to properly setup submodules after successful checkout.
#
# To enable this hook, create a symlink:
#
#     % ln -s "$PWD/githooks/post-checkout" .git/hooks/post-checkout
#
# To disable this hook, unlink it:
#
#     % unlink .git/hooks/post-checkout
#

# Arguments
prevHead="$1"
newHead="$2"
checkoutType="$3"

update_submodules() {
    ############################################################################
    # THIS FUNCTION SHOULD BE IN SYNC WITH 'post-merge'
    ############################################################################

    # First, clean/deinitialize the submodule.
    # Initialize the submodule.
    # Synchronize the submodule.
    # Finally, update/checkout the submodule.
    git submodule status 2>/dev/null \
        && (git submodule deinit --force . \
            || git submodule foreach 'rm -rf "$path"') \
        && git submodule init \
        && git submodule sync \
        && (git submodule update --init --recursive 2>/dev/null \
            || git submodule update --init \
            || git submodule update)
}

[ "$checkoutType" = 1 ] && update_submodules

unset prevHead newHead checkoutType
