#!/bin/sh
#
# A hook script to properly setup submodules after successful merge.
#
# To enable this hook, create a symlink:
#
#     % ln -s "$PWD/githooks/post-merge" .git/hooks/post-merge
#
# To disable this hook, unlink it:
#
#     % unlink .git/hooks/post-merge
#

update_submodules() {
    ############################################################################
    # THIS FUNCTION SHOULD BE IN SYNC WITH 'post-checkout'
    ############################################################################

    # First, clean/deinitialize the submodule.
    # Initialize the submodule.
    # Synchronize the submodule.
    # Finally, update/checkout the submodule.
    git submodule status 2>/dev/null \
        && (git submodule deinit --force . \
            || git submodule foreach 'rm -rf "$path"') \
        && git submodule init \
        && git submodule sync \
        && (git submodule update --init --recursive 2>/dev/null \
            || git submodule update --init \
            || git submodule update)
}

update_submodules
